language: python

dist: xenial

python: 
    - 3.7

branches:
    only:
        - master

before_install:
  - python --version
  - pip install -U pip
  - python setup.py install

install:
    - pip install -e .

script:
    - python -m pytest --color=yes 
