language: python

dist: xenial

python: 
  - 3.7

branches:
  only:
  - master

install:
  - pip install -e .[test]

script:
  - python -m pytest --color=yes --cov=sirg
    #- coverage run -m pytest

after_success:
    bash <(curl -s https://codecov.io/bash)
 
